create table if not exists public.categories (
    id integer generated by default as identity primary key,
    title text not null,
    description text not null default ''
);

create table if not exists public.authors (
    id integer generated by default as identity primary key,
    user_id uuid unique references auth.users(id) on delete cascade,
    firstname text not null,
    lastname text not null,
    avatar text not null default '',
    is_admin boolean not null default false
);

create table if not exists public.posts (
    id integer generated by default as identity primary key,
    title text not null,
    body text not null,
    thumbnail text not null,
    date_time timestamptz not null default now(),
    category_id integer references public.categories(id) on delete set null,
    author_id integer references public.authors(id) on delete cascade,
    is_featured boolean not null default false,
    is_verified boolean not null default false
);

create index if not exists posts_date_time_idx on public.posts(date_time desc);
create index if not exists posts_category_id_idx on public.posts(category_id);
create index if not exists posts_author_id_idx on public.posts(author_id);
create index if not exists authors_user_id_idx on public.authors(user_id);

do $$
begin
    if exists (
        select 1 from information_schema.columns
        where table_schema = 'public'
        and table_name = 'categories'
        and column_name = 'id'
        and is_identity = 'NO'
    ) then
        alter table public.categories alter column id add generated by default as identity;
    end if;
exception
    when duplicate_object then null;
end $$;

alter table public.categories enable row level security;
alter table public.authors enable row level security;
alter table public.posts enable row level security;

drop policy if exists "Public categories are readable" on public.categories;
create policy "Public categories are readable"
on public.categories for select
using (true);

drop policy if exists "Public authors are readable" on public.authors;
create policy "Public authors are readable"
on public.authors for select
using (true);

drop policy if exists "Users can create their author profile" on public.authors;
create policy "Users can create their author profile"
on public.authors for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can update their author profile" on public.authors;
create policy "Users can update their author profile"
on public.authors for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Admins can manage authors" on public.authors;
create policy "Admins can manage authors"
on public.authors for all
to authenticated
using (
    exists (
        select 1 from public.authors admin_author
        where admin_author.user_id = auth.uid()
        and admin_author.is_admin = true
    )
)
with check (
    exists (
        select 1 from public.authors admin_author
        where admin_author.user_id = auth.uid()
        and admin_author.is_admin = true
    )
);

drop policy if exists "Admins can manage categories" on public.categories;
create policy "Admins can manage categories"
on public.categories for all
to authenticated
using (
    exists (
        select 1 from public.authors
        where authors.user_id = auth.uid()
        and authors.is_admin = true
    )
)
with check (
    exists (
        select 1 from public.authors
        where authors.user_id = auth.uid()
        and authors.is_admin = true
    )
);

drop policy if exists "Verified posts are readable" on public.posts;
create policy "Verified posts are readable"
on public.posts for select
using (
    is_verified = true
    or exists (
        select 1 from public.authors
        where authors.id = posts.author_id
        and authors.user_id = auth.uid()
    )
    or exists (
        select 1 from public.authors
        where authors.user_id = auth.uid()
        and authors.is_admin = true
    )
);

drop policy if exists "Authenticated authors can submit posts" on public.posts;
create policy "Authenticated authors can submit posts"
on public.posts for insert
to authenticated
with check (
    is_verified = false
    and exists (
        select 1 from public.authors
        where authors.id = posts.author_id
        and authors.user_id = auth.uid()
    )
);

drop policy if exists "Authors can update own unverified posts" on public.posts;
create policy "Authors can update own unverified posts"
on public.posts for update
to authenticated
using (
    is_verified = false
    and exists (
        select 1 from public.authors
        where authors.id = posts.author_id
        and authors.user_id = auth.uid()
    )
)
with check (
    is_verified = false
    and exists (
        select 1 from public.authors
        where authors.id = posts.author_id
        and authors.user_id = auth.uid()
    )
);

drop policy if exists "Admins can manage posts" on public.posts;
create policy "Admins can manage posts"
on public.posts for all
to authenticated
using (
    exists (
        select 1 from public.authors
        where authors.user_id = auth.uid()
        and authors.is_admin = true
    )
)
with check (
    exists (
        select 1 from public.authors
        where authors.user_id = auth.uid()
        and authors.is_admin = true
    )
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.authors (user_id, firstname, lastname, avatar)
    values (
        new.id,
        coalesce(new.raw_user_meta_data->>'firstname', split_part(new.email, '@', 1)),
        coalesce(new.raw_user_meta_data->>'lastname', ''),
        coalesce(new.raw_user_meta_data->>'avatar', '1663704007ardaltunel-pp.png')
    );
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into storage.buckets (id, name, public)
values ('blog-images', 'blog-images', true)
on conflict (id) do nothing;

drop policy if exists "Public blog images are readable" on storage.objects;
create policy "Public blog images are readable"
on storage.objects for select
using (bucket_id = 'blog-images');

drop policy if exists "Authenticated users can upload blog images" on storage.objects;
create policy "Authenticated users can upload blog images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'blog-images');
