create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

create table if not exists public.categories (
    id integer generated by default as identity primary key,
    title text not null,
    description text not null default ''
);

create table if not exists public.authors (
    id integer generated by default as identity primary key,
    user_id uuid unique references auth.users(id) on delete cascade,
    firstname text not null,
    lastname text not null,
    avatar text not null default '',
    is_admin boolean not null default false
);

create table if not exists public.posts (
    id integer generated by default as identity primary key,
    title text not null,
    body text not null,
    thumbnail text not null,
    date_time timestamptz not null default now(),
    category_id integer references public.categories(id) on delete set null,
    author_id integer references public.authors(id) on delete cascade,
    is_featured boolean not null default false,
    is_verified boolean not null default false
);

create index if not exists posts_date_time_idx on public.posts(date_time desc);
create index if not exists posts_verified_date_time_idx
    on public.posts(date_time desc)
    where is_verified = true;
create index if not exists posts_category_id_idx on public.posts(category_id);
create index if not exists posts_author_id_idx on public.posts(author_id);
create index if not exists authors_user_id_idx on public.authors(user_id);

do $$
begin
    if exists (
        select 1 from information_schema.columns
        where table_schema = 'public'
          and table_name = 'categories'
          and column_name = 'id'
          and is_identity = 'NO'
    ) then
        alter table public.categories alter column id add generated by default as identity;
    end if;
exception
    when duplicate_object then null;
end $$;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'categories_title_length' and conrelid = 'public.categories'::regclass) then
        alter table public.categories add constraint categories_title_length
            check (char_length(btrim(title)) between 1 and 100) not valid;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'categories_description_length' and conrelid = 'public.categories'::regclass) then
        alter table public.categories add constraint categories_description_length
            check (char_length(description) <= 1000) not valid;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'authors_firstname_length' and conrelid = 'public.authors'::regclass) then
        alter table public.authors add constraint authors_firstname_length
            check (char_length(btrim(firstname)) between 1 and 80) not valid;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'authors_lastname_length' and conrelid = 'public.authors'::regclass) then
        alter table public.authors add constraint authors_lastname_length
            check (char_length(lastname) <= 80) not valid;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'authors_avatar_length' and conrelid = 'public.authors'::regclass) then
        alter table public.authors add constraint authors_avatar_length
            check (char_length(avatar) <= 2048) not valid;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'posts_title_length' and conrelid = 'public.posts'::regclass) then
        alter table public.posts add constraint posts_title_length
            check (char_length(btrim(title)) between 1 and 160) not valid;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'posts_body_length' and conrelid = 'public.posts'::regclass) then
        alter table public.posts add constraint posts_body_length
            check (char_length(body) between 1 and 200000) not valid;
    end if;
    if not exists (select 1 from pg_constraint where conname = 'posts_thumbnail_length' and conrelid = 'public.posts'::regclass) then
        alter table public.posts add constraint posts_thumbnail_length
            check (char_length(thumbnail) between 1 and 2048) not valid;
    end if;
end $$;

create or replace function private.is_current_user_admin()
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
    select (select auth.uid()) is not null
       and exists (
            select 1
            from public.authors
            where user_id = (select auth.uid())
              and is_admin = true
        );
$$;

revoke all on function private.is_current_user_admin() from public;
grant execute on function private.is_current_user_admin() to authenticated;

create or replace function private.protect_author_admin_role()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if tg_op = 'INSERT' then
        if new.is_admin and not private.is_current_user_admin() then
            raise exception 'Admin access cannot be self-assigned.';
        end if;
        return new;
    end if;

    if tg_op = 'UPDATE' then
        if new.is_admin is distinct from old.is_admin
           and not private.is_current_user_admin()
        then
            raise exception 'Only admins can change admin access.';
        end if;

        if old.is_admin and not new.is_admin
           and (select count(*) from public.authors where is_admin = true) <= 1
        then
            raise exception 'The final admin cannot be removed.';
        end if;
        return new;
    end if;

    if tg_op = 'DELETE' then
        if not private.is_current_user_admin() then
            raise exception 'Only admins can delete profiles.';
        end if;
        if old.is_admin
           and (select count(*) from public.authors where is_admin = true) <= 1
        then
            raise exception 'The final admin cannot be deleted.';
        end if;
        return old;
    end if;

    return null;
end;
$$;

revoke all on function private.protect_author_admin_role() from public;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    safe_firstname text;
    safe_lastname text;
begin
    safe_firstname := left(
        regexp_replace(
            coalesce(nullif(btrim(new.raw_user_meta_data->>'firstname'), ''), nullif(split_part(new.email, '@', 1), ''), 'User'),
            '[[:cntrl:]]', '', 'g'
        ),
        80
    );
    safe_lastname := left(
        regexp_replace(coalesce(new.raw_user_meta_data->>'lastname', ''), '[[:cntrl:]]', '', 'g'),
        80
    );

    insert into public.authors (user_id, firstname, lastname, avatar, is_admin)
    values (new.id, safe_firstname, safe_lastname, '1663704007ardaltunel-pp.png', false)
    on conflict (user_id) do nothing;
    return new;
end;
$$;

revoke all on function private.handle_new_user() from public;

-- Explicit IDs from imports can leave the identity sequence behind the table.
-- Keep signup-trigger inserts on the first unused author ID when this schema is reapplied.
select setval(
    pg_get_serial_sequence('public.authors', 'id'),
    coalesce((select max(id) from public.authors), 1),
    exists (select 1 from public.authors)
);

drop trigger if exists prevent_author_role_escalation on public.authors;
drop trigger if exists protect_author_admin_role on public.authors;
create trigger protect_author_admin_role
before insert or update or delete on public.authors
for each row execute function private.protect_author_admin_role();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

alter table public.categories enable row level security;
alter table public.authors enable row level security;
alter table public.posts enable row level security;

drop policy if exists "Public categories are readable" on public.categories;
drop policy if exists "Public authors are readable" on public.authors;
drop policy if exists "Users can create their author profile" on public.authors;
drop policy if exists "Users can update their author profile" on public.authors;
drop policy if exists "Admins can manage authors" on public.authors;
drop policy if exists "Admins can delete authors" on public.authors;
drop policy if exists "Admins can manage categories" on public.categories;
drop policy if exists "Admins can create categories" on public.categories;
drop policy if exists "Admins can update categories" on public.categories;
drop policy if exists "Admins can delete categories" on public.categories;
drop policy if exists "Verified posts are readable" on public.posts;
drop policy if exists "Authenticated posts are readable" on public.posts;
drop policy if exists "Authenticated authors can submit posts" on public.posts;
drop policy if exists "Authors can update own unverified posts" on public.posts;
drop policy if exists "Admins can manage posts" on public.posts;
drop policy if exists "Admins can delete posts" on public.posts;

drop function if exists public.prevent_author_role_escalation();
drop function if exists public.is_current_user_admin();
drop function if exists public.handle_new_user();

do $$
begin
    if to_regprocedure('public.rls_auto_enable()') is not null then
        execute 'revoke all on function public.rls_auto_enable() from public, anon, authenticated, service_role';
    end if;
end $$;

create policy "Public categories are readable"
on public.categories for select
to anon, authenticated
using (true);

create policy "Public authors are readable"
on public.authors for select
to anon, authenticated
using (true);

create policy "Users can create their author profile"
on public.authors for insert
to authenticated
with check (
    (user_id = (select auth.uid()) and is_admin = false)
    or (select private.is_current_user_admin())
);

create policy "Users can update their author profile"
on public.authors for update
to authenticated
using (
    user_id = (select auth.uid())
    or (select private.is_current_user_admin())
)
with check (
    user_id = (select auth.uid())
    or (select private.is_current_user_admin())
);

create policy "Admins can delete authors"
on public.authors for delete
to authenticated
using ((select private.is_current_user_admin()));

create policy "Admins can create categories"
on public.categories for insert
to authenticated
with check ((select private.is_current_user_admin()));

create policy "Admins can update categories"
on public.categories for update
to authenticated
using ((select private.is_current_user_admin()))
with check ((select private.is_current_user_admin()));

create policy "Admins can delete categories"
on public.categories for delete
to authenticated
using ((select private.is_current_user_admin()));

create policy "Verified posts are readable"
on public.posts for select
to anon
using (is_verified = true);

create policy "Authenticated posts are readable"
on public.posts for select
to authenticated
using (
    is_verified = true
    or author_id in (
        select id from public.authors where user_id = (select auth.uid())
    )
    or (select private.is_current_user_admin())
);

create policy "Authenticated authors can submit posts"
on public.posts for insert
to authenticated
with check (
    (
        is_verified = false
        and author_id in (
            select id from public.authors where user_id = (select auth.uid())
        )
    )
    or (select private.is_current_user_admin())
);

create policy "Authors can update own unverified posts"
on public.posts for update
to authenticated
using (
    (
        is_verified = false
        and author_id in (
            select id from public.authors where user_id = (select auth.uid())
        )
    )
    or (select private.is_current_user_admin())
)
with check (
    (
        is_verified = false
        and author_id in (
            select id from public.authors where user_id = (select auth.uid())
        )
    )
    or (select private.is_current_user_admin())
);

create policy "Admins can delete posts"
on public.posts for delete
to authenticated
using ((select private.is_current_user_admin()));

revoke all on table public.categories from anon, authenticated;
revoke all on table public.authors from anon, authenticated;
revoke all on table public.posts from anon, authenticated;

grant select on table public.categories to anon, authenticated;
grant select (id, firstname, lastname, avatar) on table public.authors to anon;
grant select, insert, update, delete on table public.authors to authenticated;
grant select on table public.posts to anon, authenticated;
grant insert, update, delete on table public.posts to authenticated;
revoke all on sequence public.categories_id_seq from anon, authenticated;
revoke all on sequence public.authors_id_seq from anon, authenticated;
revoke all on sequence public.posts_id_seq from anon, authenticated;
grant usage, select on sequence public.categories_id_seq to authenticated;
grant usage, select on sequence public.authors_id_seq to authenticated;
grant usage, select on sequence public.posts_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'blog-images',
    'blog-images',
    true,
    5242880,
    array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public blog images are readable" on storage.objects;
drop policy if exists "Authenticated users can upload blog images" on storage.objects;
drop policy if exists "Anyone can upload signup avatars" on storage.objects;
drop policy if exists "Users can upload their own blog images" on storage.objects;
drop policy if exists "Users can delete their own blog images" on storage.objects;

create policy "Users can upload their own blog images"
on storage.objects for insert
to authenticated
with check (
    bucket_id = 'blog-images'
    and (storage.foldername(name))[1] = 'uploads'
    and (storage.foldername(name))[2] = (select auth.uid())::text
    and lower(storage.extension(name)) in ('jpg', 'jpeg', 'png', 'webp')
);

create policy "Users can delete their own blog images"
on storage.objects for delete
to authenticated
using (
    bucket_id = 'blog-images'
    and owner_id = (select auth.uid())::text
    and (storage.foldername(name))[1] = 'uploads'
    and (storage.foldername(name))[2] = (select auth.uid())::text
);
